### ISSUE TITLE
slash command isn't typehinting to discord.Member when using typing.Union

### ISSUE THREAD

**Issue by dartmern** [dartmern/metro#1]
<img width="527" alt="image" src="https://user-images.githubusercontent.com/72849202/147291318-f49d1a32-6b95-4abc-9ee1-5b593d577cba.png">

**Comment by dartmern** [comment]
Looking on the surface it seems that you can't pass in two different types of options to discord but a fix I'll put in later is just only typehinting to **discord.User**

**Comment by JDJGInc** [comment]
🤔 discord's conversion system is weird.
