### ISSUE TITLE
When i use volume command bot disconnects it self from the vc pls fix this

### ISSUE THREAD

**Issue by GurjotSingh1105** [dartmern/metro#5]

**Comment by dartmern** [comment]
Hmm yes it does seem like it I'll find a fix. For now I'll disable the command.

**Comment by dartmern** [comment]
Seems like it's a Raspberry Pi problem. I'll try to get this fixed but currently a bit busy and it seems like the solution isn't gonna be quick.

https://github.com/freyacodes/Lavalink/issues/644
https://github.com/freyacodes/Lavalink/issues/644#issuecomment-1090419498
https://github.com/freyacodes/Lavalink/issues/519

**Comment by GurjotSingh1105** [comment]
Okay 👌

**Comment by dartmern** [comment]
Just fixed this by installing a different release of lavalink. 

[This comment](https://github.com/freyacodes/Lavalink/issues/644#issuecomment-1090419498) defiantly helped.
